
import { ChoirData, Event, AttendanceTrend, Member } from './types';

export const CHOIR_DATA: ChoirData[] = [
  { id: '1', name: 'Bicentenario', initials: 'BI', attendance: 0, streak: 0, status: 'Activo' },
  { id: '2', name: 'Bucerías', initials: 'BU', attendance: 0, streak: 0, status: 'Activo' },
  { id: '3', name: 'El Guamuchil', initials: 'EG', attendance: 0, streak: 0, status: 'Activo' },
  { id: '4', name: 'El Porvenir', initials: 'EP', attendance: 0, streak: 0, status: 'Activo' },
  { id: '5', name: 'La Peñita', initials: 'LP', attendance: 0, streak: 0, status: 'Activo' },
  { id: '6', name: 'Mezcales', initials: 'ME', attendance: 0, streak: 0, status: 'Activo' },
  { id: '7', name: 'Mezcalitos', initials: 'MT', attendance: 0, streak: 0, status: 'Activo' },
  { id: '8', name: 'Monte Sinai', initials: 'MS', attendance: 0, streak: 0, status: 'Activo' },
  { id: '9', name: 'Punta de Mita', initials: 'PM', attendance: 0, streak: 0, status: 'Activo' },
  { id: '10', name: 'San Ignacio', initials: 'SI', attendance: 0, streak: 0, status: 'Activo' },
  { id: '11', name: 'San Jose', initials: 'SJ', attendance: 0, streak: 0, status: 'Activo' },
];

export const INITIAL_EVENTS: Event[] = [
  { id: 'e1', name: 'Ensayo General Seccional', date: '2026-02-14', time: '10:00', location: 'San Ignacio', description: 'Primer encuentro masivo del año.' },
  { id: 'e2', name: 'Taller de Técnica Vocal', date: '2026-02-28', time: '09:00', location: 'Mezcales', description: 'Capacitación intensiva.' }
];

// LISTA INTEGRADA DE MIEMBROS PROPORCIONADA POR EL USUARIO
const rawMembers = [
  // MEZCALES (6) - MUJERES
  { f: "Agustina", l: "Comunidad", c: "6", v: "Por asignar", g: "Mujer" },
  { f: "Anabel", l: "Vázquez Rodríguez", c: "6", v: "Por asignar", g: "Mujer" },
  { f: "Ana", l: "Mendez Santes", c: "6", v: "Soprano", g: "Mujer" },
  { f: "Damaris Eliser", l: "Dávalos Cuevas", c: "6", v: "Soprano", g: "Mujer" },
  { f: "Daneli Silem", l: "Guzmán Rivas", c: "6", v: "Soprano", g: "Mujer" },
  { f: "Daniela Sinaí", l: "Vaca Cabrera", c: "6", v: "Soprano", g: "Mujer" },
  { f: "Erika Roxana", l: "Ventura Peña", c: "6", v: "Contralto", g: "Mujer" },
  { f: "Erminia", l: "García Ramirez", c: "6", v: "Contralto", g: "Mujer" },
  { f: "Eunice", l: "Martínez Velázquez", c: "6", v: "Contralto", g: "Mujer" },
  { f: "Eunice", l: "Vázquez Garcia", c: "6", v: "Por asignar", g: "Mujer" },
  { f: "Eva Amiel", l: "Celaya González", c: "6", v: "Soprano", g: "Mujer" },
  { f: "Felipa", l: "Cruz Sánchez", c: "6", v: "Por asignar", g: "Mujer" },
  { f: "Gloria Evelia", l: "Moreno Álvarez", c: "6", v: "Por asignar", g: "Mujer" },
  { f: "Helem Jocabed", l: "Dávalos Cuevas", c: "6", v: "Contralto", g: "Mujer" },
  { f: "Herminia", l: "García Ramirez", c: "6", v: "Contralto", g: "Mujer" },
  { f: "Isabel", l: "Peralta Soto", c: "6", v: "Por asignar", g: "Mujer" },
  { f: "Isela", l: "Mejía Peña", c: "6", v: "Soprano", g: "Mujer" },
  { f: "Julieta", l: "Pérez Nava", c: "6", v: "Por asignar", g: "Mujer" },
  { f: "Karen Darlene", l: "Torres", c: "6", v: "Por asignar", g: "Mujer" },
  { f: "Keila Saidi", l: "Flores Baños", c: "6", v: "Por asignar", g: "Mujer" },
  { f: "Keila Jabnel", l: "Villegas Díaz", c: "6", v: "Por asignar", g: "Mujer" },
  { f: "Kimberly Madai", l: "Valdovinos García", c: "6", v: "Soprano", g: "Mujer" },
  { f: "Lea", l: "Cabrera Magaña", c: "6", v: "Soprano", g: "Mujer" },
  { f: "Lidia", l: "Baños García", c: "6", v: "Por asignar", g: "Mujer" },
  { f: "Maredith Zaredt", l: "Castillo Alcanter", c: "6", v: "Contralto", g: "Mujer" },
  { f: "Martina", l: "Soto M", c: "6", v: "Por asignar", g: "Mujer" },
  { f: "Milca Jaanai", l: "Arciniega Gonzalez", c: "6", v: "Soprano", g: "Mujer" },
  { f: "Nimsy Sinaí", l: "Torres De La Torre", c: "6", v: "Por asignar", g: "Mujer" },
  { f: "Noemi", l: "González Castillo", c: "6", v: "Contralto", g: "Mujer" },
  { f: "Nohemí Alelí", l: "Celaya González", c: "6", v: "Por asignar", g: "Mujer" },
  { f: "Perla Jared", l: "Solís Mejía", c: "6", v: "Contralto", g: "Mujer" },
  { f: "Petra", l: "Espejo", c: "6", v: "Soprano", g: "Mujer" },
  { f: "Rael Betsabé", l: "Cano Alejo", c: "6", v: "Contralto", g: "Mujer" },
  { f: "Raquel", l: "Gómez Soto", c: "6", v: "Soprano", g: "Mujer" },
  { f: "Rebeca", l: "Carmona Lopez", c: "6", v: "Soprano", g: "Mujer" },
  { f: "Reyna", l: "Hernández Cruz", c: "6", v: "Por asignar", g: "Mujer" },
  { f: "Sabetai", l: "Velez", c: "6", v: "Soprano", g: "Mujer" },
  { f: "Saudí Sareb", l: "Martínez Arreola", c: "6", v: "Por asignar", g: "Mujer" },
  { f: "Zurisadaí", l: "Sánchez Vázquez", c: "6", v: "Soprano", g: "Mujer" },
  
  // MEZCALES (6) - HOMBRES
  { f: "Atlai", l: "Sánchez Martines", c: "6", v: "Tenor", g: "Hombre" },
  { f: "Bani Joacim", l: "Guzmán Rivas", c: "6", v: "Tenor", g: "Hombre" },
  { f: "Bardomieno", l: "González Flores", c: "6", v: "Bajo", g: "Hombre" },
  { f: "Cándido", l: "Martínez García", c: "6", v: "Por asignar", g: "Hombre" },
  { f: "César", l: "Morales (Mara Ciegos)", c: "6", v: "Por asignar", g: "Hombre" },
  { f: "David Israel", l: "Vaca Cabrera", c: "6", v: "Bajo", g: "Hombre" },
  { f: "Eli", l: "Arciniega Quezada", c: "6", v: "Bajo", g: "Hombre" },
  { f: "Ezequiel Loai", l: "Sánchez", c: "6", v: "Tenor", g: "Hombre" },
  { f: "Jaime", l: "Panuco Hernandez", c: "6", v: "Bajo", g: "Hombre" },
  { f: "Jesus", l: "Vázquez", c: "6", v: "Por asignar", g: "Hombre" },
  { f: "Joel", l: "Aguilar Martinez", c: "6", v: "Bajo", g: "Hombre" },
  { f: "Jonathan", l: "Vélez Espejo", c: "6", v: "Bajo", g: "Hombre" },
  { f: "José", l: "Hernández Flores", c: "6", v: "Por asignar", g: "Hombre" },
  { f: "José Ángel", l: "Hernández Álvarez", c: "6", v: "Por asignar", g: "Hombre" },
  { f: "Josue Baroilai", l: "Cano Alejo", c: "6", v: "Bajo", g: "Hombre" },
  { f: "Josue Salvador", l: "Alcaster Camargo", c: "6", v: "Por asignar", g: "Hombre" },
  { f: "Juan Eliasib", l: "Marin Gonzalez", c: "6", v: "Bajo", g: "Hombre" },
  { f: "Juan Marcos", l: "Flores Espinosa", c: "6", v: "Tenor", g: "Hombre" },
  { f: "Juan Pablo", l: "Sánchez Vázquez", c: "6", v: "Tenor", g: "Hombre" },
  { f: "Juan Sebastian", l: "Tabon Suarez", c: "6", v: "Bajo", g: "Hombre" },
  { f: "Matias Orelo", l: "Chavez Castañeda", c: "6", v: "Bajo", g: "Hombre" },
  { f: "Natanael Radai", l: "Tapia Aguilar", c: "6", v: "Por asignar", g: "Hombre" },
  { f: "Roberto", l: "Celaya", c: "6", v: "Por asignar", g: "Hombre" },
  { f: "Tomás", l: "Vélez Castro", c: "6", v: "Por asignar", g: "Hombre" },
  { f: "Zuriel Atlai", l: "Vélez Espejo", c: "6", v: "Por asignar", g: "Hombre" },

  // SAN IGNACIO (10)
  { f: "Dulce Esmeralda", l: "Benites Valdovinos", c: "10", v: "Por asignar", g: "Mujer" },
  { f: "Esmeralda", l: "Pérez Flores", c: "10", v: "Soprano", g: "Mujer" },
  { f: "Gloria", l: "Calvillo", c: "10", v: "Contralto", g: "Mujer" },
  { f: "Kimberli", l: "Villalobos", c: "10", v: "Contralto", g: "Mujer" },
  { f: "María Belén", l: "Benites Valdovinos", c: "10", v: "Por asignar", g: "Mujer" },
  { f: "Ángel De Jesús", l: "Pacheco", c: "10", v: "Bajo", g: "Hombre" },
  { f: "Eliel", l: "Ipiña", c: "10", v: "Tenor", g: "Hombre" },
  { f: "Jhonatan", l: "Cordoba", c: "10", v: "Bajo", g: "Hombre" },
  { f: "José Manuel", l: "Pérez Flores", c: "10", v: "Por asignar", g: "Hombre" },
  { f: "Ruben Adriel", l: "Ipiña Poot", c: "10", v: "Por asignar", g: "Hombre" },

  // BICENTENARIO (1)
  { f: "Agapito", l: "Sánchez", c: "1", v: "Bajo", g: "Hombre" },
  { f: "Ashley Jozabed", l: "Valle Alvarado", c: "1", v: "Soprano", g: "Mujer" },
  { f: "Baní Jocsan", l: "---", c: "1", v: "Tenor", g: "Hombre" },
  { f: "Betzan", l: "Ramos", c: "1", v: "Contralto", g: "Mujer" },
  { f: "Cleotilde", l: "Sanchez", c: "1", v: "Contralto", g: "Mujer" },
  { f: "Emilia", l: "Castro Ciriaco", c: "1", v: "Soprano", g: "Mujer" },
  { f: "Estela Victoria", l: "Montes", c: "1", v: "Soprano", g: "Mujer" },
  { f: "Habram", l: "---", c: "1", v: "Tenor", g: "Hombre" },
  { f: "Herem", l: "Joya", c: "1", v: "Contralto", g: "Mujer" },
  { f: "Jezrel", l: "---", c: "1", v: "Tenor", g: "Hombre" },
  { f: "Jordan", l: "Joya", c: "1", v: "Bajo", g: "Hombre" },
  { f: "Nimsi Samir", l: "Valle Castillón", c: "1", v: "Soprano", g: "Mujer" },

  // BUCERIAS (2)
  { f: "Florencia", l: "García Castillo", c: "2", v: "Soprano", g: "Mujer" },
  { f: "Jair Ezequiel", l: "Toriz Rodríguez", c: "2", v: "Tenor", g: "Hombre" },
  { f: "Moisés Abisai", l: "Sánchez García", c: "2", v: "Tenor", g: "Hombre" },
  { f: "Nahomi", l: "Hernandez Urieta", c: "2", v: "Soprano", g: "Mujer" },
  { f: "Rodrigo", l: "Sánchez Reyes", c: "2", v: "Bajo", g: "Hombre" },
  { f: "Samai", l: "Urieta Perez", c: "2", v: "Contralto", g: "Mujer" },
  { f: "Zabdi", l: "Gutierrez", c: "2", v: "Soprano", g: "Mujer" },

  // EL GUAMUCHIL (3)
  { f: "Amsi Abigail", l: "Mena Antonio", c: "3", v: "Contralto", g: "Mujer" },
  { f: "Brayan", l: "Rodriguez", c: "3", v: "Tenor", g: "Hombre" },
  { f: "Eunice", l: "Antonio Pérez", c: "3", v: "Contralto", g: "Mujer" },
  { f: "Ezbai", l: "Bernal", c: "3", v: "Contralto", g: "Mujer" },
  { f: "Jepte Azael", l: "Mena", c: "3", v: "Por asignar", g: "Hombre" },
  { f: "Jorge Naason", l: "Bernal", c: "3", v: "Bajo", g: "Hombre" },

  // EL PORVENIR (4)
  { f: "Álvaro", l: "Mejía Peña", c: "4", v: "Bajo", g: "Hombre" },
  { f: "Belen", l: "Huerta Lara", c: "4", v: "Soprano", g: "Mujer" },
  { f: "Ezequiel", l: "Ortiz", c: "4", v: "Tenor", g: "Hombre" },
  { f: "Gared", l: "Rangel", c: "4", v: "Por asignar", g: "Hombre" },
  { f: "Juan Antonio", l: "Alvarez", c: "4", v: "Tenor", g: "Hombre" },
  { f: "Mizraim", l: "Rangel", c: "4", v: "Por asignar", g: "Hombre" },
  { f: "Rebeca", l: "Mata", c: "4", v: "Soprano", g: "Mujer" },
  { f: "Tereso", l: "Pérez Román", c: "4", v: "Tenor", g: "Hombre" },
  { f: "Zuri", l: "Huerta", c: "4", v: "Contralto", g: "Mujer" },

  // LA PEÑITA (5)
  { f: "Alejandra", l: "López Ocampo", c: "5", v: "Soprano", g: "Mujer" },
  { f: "Alicia Naharai", l: "Nuño y Siordia", c: "5", v: "Soprano", g: "Mujer" },
  { f: "Alma", l: "Hernandez", c: "5", v: "Contralto", g: "Mujer" },
  { f: "Armando", l: "Ruiz Salgado", c: "5", v: "Bajo", g: "Hombre" },
  { f: "Azael", l: "Ramirez", c: "5", v: "Tenor", g: "Hombre" },
  { f: "Dalila", l: "Ruiz", c: "5", v: "Contralto", g: "Mujer" },
  { f: "Enoc", l: "Hernandez", c: "5", v: "Bajo", g: "Hombre" },
  { f: "Enoc", l: "Hernandez JR", c: "5", v: "Tenor", g: "Hombre" },
  { f: "Fernanda", l: "Nuño", c: "5", v: "Contralto", g: "Mujer" },
  { f: "Gabriel", l: "Ayala", c: "5", v: "Tenor", g: "Hombre" },
  { f: "Jose", l: "Alvarez Ibarra", c: "5", v: "Tenor", g: "Hombre" },
  { f: "Joselin", l: "Alvarez", c: "5", v: "Soprano", g: "Mujer" },
  { f: "Karla Mónica", l: "López Ocampo", c: "5", v: "Soprano", g: "Mujer" },
  { f: "Mareza", l: "Rufino", c: "5", v: "Contralto", g: "Mujer" },
  { f: "Quiriet", l: "Hernandez", c: "5", v: "Soprano", g: "Mujer" },
  { f: "Zabdi", l: "Díaz Ventura", c: "5", v: "Contralto", g: "Mujer" },
  { f: "Zabdi", l: "Sigala", c: "5", v: "Soprano", g: "Mujer" },

  // MEZCALITOS (7)
  { f: "Alicia", l: "Angeles", c: "7", v: "Por asignar", g: "Mujer" },
  { f: "Elias Josafat", l: "Romero Santos", c: "7", v: "Por asignar", g: "Hombre" },
  { f: "Fernando", l: "Romero", c: "7", v: "Por asignar", g: "Hombre" },
  { f: "Jared", l: "Ramirez Gomez", c: "7", v: "Por asignar", g: "Hombre" },
  { f: "Javi", l: "Jimenez", c: "7", v: "Por asignar", g: "Hombre" },
  { f: "Obed Natanael", l: "Ramirez Gomez", c: "7", v: "Por asignar", g: "Hombre" },

  // MONTE SINAI (8)
  { f: "Abdiel", l: "Vargas Hernandez", c: "8", v: "Bajo", g: "Hombre" },
  { f: "Abner", l: "Vargas Hernandez", c: "8", v: "Bajo", g: "Hombre" },
  { f: "Asael", l: "Dominguez", c: "8", v: "Por asignar", g: "Hombre" },
  { f: "Belen", l: "Sanchez", c: "8", v: "Por asignar", g: "Mujer" },
  { f: "Cristi", l: "Ruiz", c: "8", v: "Por asignar", g: "Mujer" },
  { f: "Esther", l: "Hernández Juárez", c: "8", v: "Contralto", g: "Mujer" },
  { f: "Isaac", l: "Herrera Gonzaga", c: "8", v: "Tenor", g: "Hombre" },
  { f: "Maribel", l: "Herrera Campos", c: "8", v: "Por asignar", g: "Mujer" },
  { f: "Sabdy Bira", l: "Romero Alejo", c: "8", v: "Contralto", g: "Mujer" },
  { f: "Samai", l: "Romero Alejo", c: "8", v: "Contralto", g: "Mujer" },
  { f: "Sua Merab", l: "Vargas Acevedo", c: "8", v: "Contralto", g: "Mujer" },
  { f: "Susan", l: "Ruiz", c: "8", v: "Por asignar", g: "Mujer" },
  { f: "Yareth Sismai", l: "Vargas Acevedo", c: "8", v: "Soprano", g: "Mujer" },

  // PUNTA DE MITA (9)
  { f: "Aida", l: "Aguilera", c: "9", v: "Por asignar", g: "Mujer" },
  { f: "Atlai", l: "Cortez", c: "9", v: "Por asignar", g: "Hombre" },
  { f: "Becke", l: "Cocolan", c: "9", v: "Por asignar", g: "Mujer" },
  { f: "Elisa", l: "Aguilera Mantecón", c: "9", v: "Soprano", g: "Mujer" },
  { f: "Esperanza", l: "Mantecon Hernandez", c: "9", v: "Contralto", g: "Mujer" },
  { f: "Madai", l: "Gomez Garcia", c: "9", v: "Por asignar", g: "Mujer" },
  { f: "Noe", l: "Pelayo", c: "9", v: "Por asignar", g: "Hombre" },
  { f: "Saudi Sarai", l: "Aguilar Arciniega", c: "9", v: "Por asignar", g: "Mujer" },

  // SAN JOSE (11)
  { f: "Alma", l: "Sanchez Villanueva", c: "11", v: "Contralto", g: "Mujer" },
  { f: "Andrea Celeste", l: "Robles Flores", c: "11", v: "Soprano", g: "Mujer" },
  { f: "Andrea", l: "Juan Apolonio", c: "11", v: "Soprano", g: "Mujer" },
  { f: "Angel", l: "Juan Apolonio", c: "11", v: "Bajo", g: "Hombre" },
  { f: "Etni Ezbai", l: "Martinez Sanchez", c: "11", v: "Soprano", g: "Mujer" },
  { f: "Imelda", l: "Mendez Urbano", c: "11", v: "Soprano", g: "Mujer" },
  { f: "Keyla Merary", l: "Salvador Hernández", c: "11", v: "Por asignar", g: "Mujer" },
  { f: "Magdiel Manases", l: "Salazar Sanchez", c: "11", v: "Bajo", g: "Hombre" },
  { f: "Maria de los Angeles", l: "Garcia", c: "11", v: "Soprano", g: "Mujer" },
  { f: "Nataly Nicole", l: "Miguez Zamora", c: "11", v: "Contralto", g: "Mujer" },
  { f: "Rahel Sismai", l: "Salvador Hernandez", c: "11", v: "Contralto", g: "Mujer" },
  { f: "Siria Galilea", l: "Salvador Hernandez", c: "11", v: "Soprano", g: "Mujer" },
  { f: "Tirsa Narai", l: "Cortes Sanchez", c: "11", v: "Contralto", g: "Mujer" },
  { f: "Victor Azael", l: "Mariles Roble", c: "11", v: "Bajo", g: "Hombre" }
];

export const INITIAL_MEMBERS: Member[] = rawMembers.map((m, i) => ({
  id: `m-init-${i}`,
  firstName: m.f,
  lastName: m.l,
  email: `${m.f.toLowerCase().replace(/\s/g, '')}@esperanza.com`,
  choirId: m.c,
  voiceType: m.v as Member['voiceType'],
  gender: m.g as Member['gender']
}));

export const ATTENDANCE_TRENDS: AttendanceTrend[] = [
  { month: 'ENE', value: 0 },
  { month: 'FEB', value: 0 },
  { month: 'MAR', value: 0 },
];
